services:
  - type: web
    name: vitalsense-backend
    runtime: python
    buildCommand: python -m pip install -r requirements.txt
    startCommand: python main.py
    rootDir: vitalsense-backend
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
