# Extracted from frontend exercises
EXERCISES = [
  {"id": 'push_ups', "name": 'Push-ups', "muscleGroup": 'chest', "gymRequired": 'home', "unsafeFor": ['shoulder_injury', 'wrist_pain']},
  {"id": 'wide_push_ups', "name": 'Wide Push-ups', "muscleGroup": 'chest', "gymRequired": 'home', "unsafeFor": ['shoulder_injury', 'wrist_pain']},
  {"id": 'diamond_push_ups', "name": 'Diamond Push-ups', "muscleGroup": 'chest', "gymRequired": 'home', "unsafeFor": ['shoulder_injury', 'wrist_pain']},
  {"id": 'decline_push_ups', "name": 'Decline Push-ups', "muscleGroup": 'chest', "gymRequired": 'home', "unsafeFor": ['shoulder_injury', 'wrist_pain', 'high_blood_pressure']},
  {"id": 'pike_push_ups', "name": 'Pike Push-ups', "muscleGroup": 'chest', "gymRequired": 'home', "unsafeFor": ['shoulder_injury', 'wrist_pain', 'high_blood_pressure']},
  {"id": 'db_bench_press', "name": 'Dumbbell Bench Press', "muscleGroup": 'chest', "gymRequired": 'small_gym', "unsafeFor": ['shoulder_injury']},
  {"id": 'db_flyes', "name": 'Dumbbell Flyes', "muscleGroup": 'chest', "gymRequired": 'small_gym', "unsafeFor": ['shoulder_injury']},
  {"id": 'incline_db_press', "name": 'Incline Dumbbell Press', "muscleGroup": 'chest', "gymRequired": 'small_gym', "unsafeFor": ['shoulder_injury']},
  {"id": 'bench_press', "name": 'Barbell Bench Press', "muscleGroup": 'chest', "gymRequired": 'big_gym', "unsafeFor": ['shoulder_injury']},
  {"id": 'cable_crossover', "name": 'Cable Crossover', "muscleGroup": 'chest', "gymRequired": 'big_gym', "unsafeFor": ['shoulder_injury']},
  {"id": 'chest_press_machine', "name": 'Chest Press Machine', "muscleGroup": 'chest', "gymRequired": 'big_gym', "unsafeFor": ['shoulder_injury']},
  {"id": 'pec_deck', "name": 'Pec Deck', "muscleGroup": 'chest', "gymRequired": 'big_gym', "unsafeFor": ['shoulder_injury']},
  {"id": 'incline_bench_press', "name": 'Incline Barbell Press', "muscleGroup": 'chest', "gymRequired": 'big_gym', "unsafeFor": ['shoulder_injury']},
  {"id": 'superman', "name": 'Superman', "muscleGroup": 'back', "gymRequired": 'home', "unsafeFor": ['severe_back_pain']},
  {"id": 'reverse_snow_angels', "name": 'Reverse Snow Angels', "muscleGroup": 'back', "gymRequired": 'home', "unsafeFor": ['shoulder_injury']},
  {"id": 'door_frame_rows', "name": 'Door Frame Rows', "muscleGroup": 'back', "gymRequired": 'home', "unsafeFor": []},
  {"id": 'db_rows', "name": 'Dumbbell Rows', "muscleGroup": 'back', "gymRequired": 'small_gym', "unsafeFor": ['lower_back_pain']},
  {"id": 'bent_over_rows', "name": 'Bent Over Rows', "muscleGroup": 'back', "gymRequired": 'small_gym', "unsafeFor": ['lower_back_pain']},
  {"id": 'pull_ups', "name": 'Pull-ups', "muscleGroup": 'back', "gymRequired": 'small_gym', "unsafeFor": ['shoulder_injury']},
  {"id": 'lat_pulldown_small', "name": 'Lat Pulldown', "muscleGroup": 'back', "gymRequired": 'small_gym', "unsafeFor": ['shoulder_injury']},
  {"id": 'lat_pulldown_machine', "name": 'Lat Pulldown Machine', "muscleGroup": 'back', "gymRequired": 'big_gym', "unsafeFor": ['shoulder_injury']},
  {"id": 'cable_rows', "name": 'Cable Rows', "muscleGroup": 'back', "gymRequired": 'big_gym', "unsafeFor": ['lower_back_pain']},
  {"id": 't_bar_row', "name": 'T-Bar Row', "muscleGroup": 'back', "gymRequired": 'big_gym', "unsafeFor": ['lower_back_pain']},
  {"id": 'seated_row_machine', "name": 'Seated Row Machine', "muscleGroup": 'back', "gymRequired": 'big_gym', "unsafeFor": []},
  {"id": 'deadlift', "name": 'Deadlift', "muscleGroup": 'back', "gymRequired": 'big_gym', "unsafeFor": ['lower_back_pain', 'knee_pain']},
  {"id": 'lateral_raises_bottles', "name": 'Lateral Raises (Water Bottles)', "muscleGroup": 'shoulders', "gymRequired": 'home', "unsafeFor": ['shoulder_injury']},
  {"id": 'front_raises_home', "name": 'Front Raises', "muscleGroup": 'shoulders', "gymRequired": 'home', "unsafeFor": ['shoulder_injury']},
  {"id": 'db_shoulder_press', "name": 'Dumbbell Shoulder Press', "muscleGroup": 'shoulders', "gymRequired": 'small_gym', "unsafeFor": ['shoulder_injury']},
  {"id": 'lateral_raises', "name": 'Lateral Raises', "muscleGroup": 'shoulders', "gymRequired": 'small_gym', "unsafeFor": ['shoulder_injury']},
  {"id": 'front_raises', "name": 'Front Raises', "muscleGroup": 'shoulders', "gymRequired": 'small_gym', "unsafeFor": ['shoulder_injury']},
  {"id": 'arnold_press', "name": 'Arnold Press', "muscleGroup": 'shoulders', "gymRequired": 'small_gym', "unsafeFor": ['shoulder_injury']},
  {"id": 'bb_overhead_press', "name": 'Barbell Overhead Press', "muscleGroup": 'shoulders', "gymRequired": 'big_gym', "unsafeFor": ['shoulder_injury', 'lower_back_pain']},
  {"id": 'cable_lateral_raises', "name": 'Cable Lateral Raises', "muscleGroup": 'shoulders', "gymRequired": 'big_gym', "unsafeFor": ['shoulder_injury']},
  {"id": 'machine_shoulder_press', "name": 'Machine Shoulder Press', "muscleGroup": 'shoulders', "gymRequired": 'big_gym', "unsafeFor": ['shoulder_injury']},
  {"id": 'face_pulls', "name": 'Face Pulls', "muscleGroup": 'shoulders', "gymRequired": 'big_gym', "unsafeFor": []},
  {"id": 'chin_ups', "name": 'Chin-ups', "muscleGroup": 'biceps', "gymRequired": 'home', "unsafeFor": ['shoulder_injury']},
  {"id": 'towel_curls', "name": 'Towel Curls', "muscleGroup": 'biceps', "gymRequired": 'home', "unsafeFor": []},
  {"id": 'band_curls', "name": 'Resistance Band Curls', "muscleGroup": 'biceps', "gymRequired": 'home', "unsafeFor": []},
  {"id": 'db_curls', "name": 'Dumbbell Curls', "muscleGroup": 'biceps', "gymRequired": 'small_gym', "unsafeFor": []},
  {"id": 'hammer_curls', "name": 'Hammer Curls', "muscleGroup": 'biceps', "gymRequired": 'small_gym', "unsafeFor": []},
  {"id": 'concentration_curls', "name": 'Concentration Curls', "muscleGroup": 'biceps', "gymRequired": 'small_gym', "unsafeFor": []},
  {"id": 'preacher_curls', "name": 'Preacher Curls', "muscleGroup": 'biceps', "gymRequired": 'small_gym', "unsafeFor": []},
  {"id": 'bb_curls', "name": 'Barbell Curls', "muscleGroup": 'biceps', "gymRequired": 'big_gym', "unsafeFor": ['wrist_pain']},
  {"id": 'cable_curls', "name": 'Cable Curls', "muscleGroup": 'biceps', "gymRequired": 'big_gym', "unsafeFor": []},
  {"id": 'machine_curls', "name": 'Machine Curls', "muscleGroup": 'biceps', "gymRequired": 'big_gym', "unsafeFor": []},
  {"id": 'spider_curls', "name": 'Spider Curls', "muscleGroup": 'biceps', "gymRequired": 'big_gym', "unsafeFor": []},
  {"id": 'tricep_dips_chair', "name": 'Tricep Dips (Chair)', "muscleGroup": 'triceps', "gymRequired": 'home', "unsafeFor": ['shoulder_injury', 'wrist_pain']},
  {"id": 'overhead_tricep_bottle', "name": 'Overhead Tricep Extension', "muscleGroup": 'triceps', "gymRequired": 'home', "unsafeFor": ['shoulder_injury']},
  {"id": 'overhead_tricep_ext', "name": 'Overhead Tricep Extension', "muscleGroup": 'triceps', "gymRequired": 'small_gym', "unsafeFor": ['shoulder_injury']},
  {"id": 'kickbacks', "name": 'Kickbacks', "muscleGroup": 'triceps', "gymRequired": 'small_gym', "unsafeFor": []},
  {"id": 'skull_crushers', "name": 'Skull Crushers (Dumbbells)', "muscleGroup": 'triceps', "gymRequired": 'small_gym', "unsafeFor": ['elbow_pain']},
  {"id": 'cable_pushdown', "name": 'Cable Pushdown', "muscleGroup": 'triceps', "gymRequired": 'big_gym', "unsafeFor": []},
  {"id": 'rope_pushdown', "name": 'Rope Pushdown', "muscleGroup": 'triceps', "gymRequired": 'big_gym', "unsafeFor": []},
  {"id": 'machine_dips', "name": 'Machine Dips', "muscleGroup": 'triceps', "gymRequired": 'big_gym', "unsafeFor": ['shoulder_injury']},
  {"id": 'close_grip_bench', "name": 'Close Grip Bench Press', "muscleGroup": 'triceps', "gymRequired": 'big_gym', "unsafeFor": ['wrist_pain']},
  {"id": 'squats', "name": 'Squats', "muscleGroup": 'legs', "gymRequired": 'home', "unsafeFor": ['severe_knee_pain']},
  {"id": 'lunges', "name": 'Lunges', "muscleGroup": 'legs', "gymRequired": 'home', "unsafeFor": ['knee_pain']},
  {"id": 'glute_bridges', "name": 'Glute Bridges', "muscleGroup": 'legs', "gymRequired": 'home', "unsafeFor": []},
  {"id": 'wall_sit', "name": 'Wall Sit', "muscleGroup": 'legs', "gymRequired": 'home', "unsafeFor": ['knee_pain']},
  {"id": 'calf_raises', "name": 'Calf Raises', "muscleGroup": 'legs', "gymRequired": 'home', "unsafeFor": []},
  {"id": 'jump_squats', "name": 'Jump Squats', "muscleGroup": 'legs', "gymRequired": 'home', "unsafeFor": ['knee_pain', 'back_pain']},
  {"id": 'db_squats', "name": 'Dumbbell Squats', "muscleGroup": 'legs', "gymRequired": 'small_gym', "unsafeFor": ['knee_pain', 'lower_back_pain']},
  {"id": 'rdl', "name": 'Romanian Deadlift', "muscleGroup": 'legs', "gymRequired": 'small_gym', "unsafeFor": ['lower_back_pain']},
  {"id": 'db_lunges', "name": 'Dumbbell Lunges', "muscleGroup": 'legs', "gymRequired": 'small_gym', "unsafeFor": ['knee_pain']},
  {"id": 'step_ups', "name": 'Step-ups', "muscleGroup": 'legs', "gymRequired": 'small_gym', "unsafeFor": ['knee_pain']},
  {"id": 'goblet_squat', "name": 'Goblet Squat', "muscleGroup": 'legs', "gymRequired": 'small_gym', "unsafeFor": ['severe_knee_pain']},
  {"id": 'bb_squat', "name": 'Barbell Squat', "muscleGroup": 'legs', "gymRequired": 'big_gym', "unsafeFor": ['knee_pain', 'back_pain']},
  {"id": 'leg_press', "name": 'Leg Press', "muscleGroup": 'legs', "gymRequired": 'big_gym', "unsafeFor": ['severe_knee_pain']},
  {"id": 'leg_extension', "name": 'Leg Extension', "muscleGroup": 'legs', "gymRequired": 'big_gym', "unsafeFor": ['knee_pain']},
  {"id": 'leg_curl', "name": 'Leg Curl', "muscleGroup": 'legs', "gymRequired": 'big_gym', "unsafeFor": []},
  {"id": 'hack_squat', "name": 'Hack Squat', "muscleGroup": 'legs', "gymRequired": 'big_gym', "unsafeFor": ['knee_pain']},
  {"id": 'smith_machine_squat', "name": 'Smith Machine Squat', "muscleGroup": 'legs', "gymRequired": 'big_gym', "unsafeFor": ['knee_pain']},
  {"id": 'hip_thrust', "name": 'Hip Thrust', "muscleGroup": 'legs', "gymRequired": 'big_gym', "unsafeFor": ['back_pain']},
  {"id": 'plank', "name": 'Plank', "muscleGroup": 'core', "gymRequired": 'home', "unsafeFor": ['lower_back_pain']},
  {"id": 'crunches', "name": 'Crunches', "muscleGroup": 'core', "gymRequired": 'home', "unsafeFor": ['neck_pain', 'lower_back_pain']},
  {"id": 'bicycle_crunches', "name": 'Bicycle Crunches', "muscleGroup": 'core', "gymRequired": 'home', "unsafeFor": ['lower_back_pain']},
  {"id": 'leg_raises', "name": 'Leg Raises', "muscleGroup": 'core', "gymRequired": 'home', "unsafeFor": ['lower_back_pain']},
  {"id": 'russian_twists', "name": 'Russian Twists', "muscleGroup": 'core', "gymRequired": 'home', "unsafeFor": ['lower_back_pain']},
  {"id": 'mountain_climbers', "name": 'Mountain Climbers', "muscleGroup": 'core', "gymRequired": 'home', "unsafeFor": ['wrist_pain']},
  {"id": 'dead_bug', "name": 'Dead Bug', "muscleGroup": 'core', "gymRequired": 'home', "unsafeFor": []},
  {"id": 'cable_crunches', "name": 'Cable Crunches', "muscleGroup": 'core', "gymRequired": 'small_gym', "unsafeFor": ['lower_back_pain']},
  {"id": 'ab_wheel', "name": 'Ab Wheel', "muscleGroup": 'core', "gymRequired": 'small_gym', "unsafeFor": ['lower_back_pain', 'shoulder_injury']},
  {"id": 'hanging_leg_raises', "name": 'Hanging Leg Raises', "muscleGroup": 'core', "gymRequired": 'small_gym', "unsafeFor": ['shoulder_injury', 'lower_back_pain']},
  {"id": 'decline_crunches', "name": 'Decline Crunches', "muscleGroup": 'core', "gymRequired": 'small_gym', "unsafeFor": ['high_blood_pressure']},
  {"id": 'jumping_jacks', "name": 'Jumping Jacks', "muscleGroup": 'cardio', "gymRequired": 'home', "unsafeFor": ['knee_pain', 'joint_pain']},
  {"id": 'high_knees', "name": 'High Knees', "muscleGroup": 'cardio', "gymRequired": 'home', "unsafeFor": ['knee_pain']},
  {"id": 'burpees', "name": 'Burpees', "muscleGroup": 'cardio', "gymRequired": 'home', "unsafeFor": ['knee_pain', 'shoulder_injury', 'back_pain']},
  {"id": 'jump_rope', "name": 'Jump Rope', "muscleGroup": 'cardio', "gymRequired": 'home', "unsafeFor": ['knee_pain']},
  {"id": 'shadow_boxing', "name": 'Shadow Boxing', "muscleGroup": 'cardio', "gymRequired": 'home', "unsafeFor": ['shoulder_injury']},
  {"id": 'treadmill_walk', "name": 'Treadmill Walk', "muscleGroup": 'cardio', "gymRequired": 'small_gym', "unsafeFor": []},
  {"id": 'stationary_bike', "name": 'Stationary Bike', "muscleGroup": 'cardio', "gymRequired": 'small_gym', "unsafeFor": []},
  {"id": 'elliptical', "name": 'Elliptical', "muscleGroup": 'cardio', "gymRequired": 'small_gym', "unsafeFor": []},
  {"id": 'treadmill_run', "name": 'Treadmill Run', "muscleGroup": 'cardio', "gymRequired": 'big_gym', "unsafeFor": ['knee_pain', 'back_pain']},
  {"id": 'rowing_machine', "name": 'Rowing Machine', "muscleGroup": 'cardio', "gymRequired": 'big_gym', "unsafeFor": ['lower_back_pain']},
  {"id": 'stairmaster', "name": 'StairMaster', "muscleGroup": 'cardio', "gymRequired": 'big_gym', "unsafeFor": ['knee_pain']},
  {"id": 'battle_ropes', "name": 'Battle Ropes', "muscleGroup": 'cardio', "gymRequired": 'big_gym', "unsafeFor": ['shoulder_injury', 'back_pain']},
  {"id": 'assault_bike', "name": 'Assault Bike', "muscleGroup": 'cardio', "gymRequired": 'big_gym', "unsafeFor": ['shoulder_injury', 'knee_pain']},
  {"id": 'walking', "name": 'Walking', "muscleGroup": 'cardio', "gymRequired": 'home', "unsafeFor": []},
  {"id": 'seated_leg_raises', "name": 'Seated Leg Raises', "muscleGroup": 'legs', "gymRequired": 'home', "unsafeFor": []},
  {"id": 'chair_squats', "name": 'Chair Squats', "muscleGroup": 'legs', "gymRequired": 'home', "unsafeFor": ['severe_knee_pain']},
  {"id": 'stretching_routine', "name": 'Stretching Routine', "muscleGroup": 'full_body', "gymRequired": 'home', "unsafeFor": []},
]
