LEBANESE_FOODS = [
    { "id": "m01", "name": "Baba Ghanouj", "arabicName": "بابا غنوج", "category": "main", "calories": 90, "protein": 2, "carbs": 6, "fat": 7, "serving": "100g" },
    { "id": "m02", "name": "Batata Mahchi", "arabicName": "بطاطا محشي", "category": "main", "calories": 128, "protein": 4.8, "carbs": 15.2, "fat": 5.6, "serving": "100g" },
    { "id": "m03", "name": "Borgul bi Banadoura", "arabicName": "برغل بالبندورة", "category": "main", "calories": 130, "protein": 4, "carbs": 24, "fat": 2.5, "serving": "100g" },
    { "id": "m04", "name": "Chichbarak", "arabicName": "شيشبرك", "category": "main", "calories": 126, "protein": 6, "carbs": 11.6, "fat": 6, "serving": "100g" },
    { "id": "m05", "name": "Falafel", "arabicName": "فلافل", "category": "main", "calories": 226, "protein": 9.3, "carbs": 21.3, "fat": 12, "serving": "100g" },
    { "id": "m06", "name": "Fatayer Sabanikh", "arabicName": "فطاير سبانخ", "category": "main", "calories": 186, "protein": 5.3, "carbs": 20, "fat": 9.3, "serving": "100g" },
    { "id": "m07", "name": "Fattat Hommos", "arabicName": "فتّة حمّص", "category": "main", "calories": 120, "protein": 4.5, "carbs": 12, "fat": 6.2, "serving": "100g" },
    { "id": "m08", "name": "Fattoush", "arabicName": "فتّوش", "category": "main", "calories": 60, "protein": 1.3, "carbs": 7.3, "fat": 3, "serving": "100g" },
    { "id": "m09", "name": "Foul Moudamas", "arabicName": "فول مدمّس", "category": "main", "calories": 112, "protein": 6.4, "carbs": 15.2, "fat": 2.4, "serving": "100g" },
    { "id": "m10", "name": "Hindbe bil Zet", "arabicName": "هندبة بالزيت", "category": "main", "calories": 75, "protein": 2, "carbs": 4, "fat": 6, "serving": "100g" },
    { "id": "m11", "name": "Hommos bi Tahini", "arabicName": "حمّص بالطحينة", "category": "main", "calories": 175, "protein": 6, "carbs": 16, "fat": 10, "serving": "100g" },
    { "id": "m12", "name": "Kafta wa Batata", "arabicName": "كفتة وبطاطا", "category": "main", "calories": 128, "protein": 6.8, "carbs": 8.5, "fat": 7.4, "serving": "100g" },
    { "id": "m13", "name": "Kebba bil Sayniya", "arabicName": "كبّة بالصينية", "category": "main", "calories": 210, "protein": 11, "carbs": 14, "fat": 12, "serving": "100g" },
    { "id": "m14", "name": "Koussa Mahchi", "arabicName": "كوسا محشي", "category": "main", "calories": 124, "protein": 5.6, "carbs": 11.2, "fat": 6.4, "serving": "100g" },
    { "id": "m15", "name": "Lahm bil Ajin", "arabicName": "لحم بعجين", "category": "main", "calories": 211, "protein": 10, "carbs": 21, "fat": 8.8, "serving": "100g" },
    { "id": "m16", "name": "Loubia bil Zet", "arabicName": "لوبيا بالزيت", "category": "main", "calories": 88, "protein": 3.2, "carbs": 11.2, "fat": 4, "serving": "100g" },
    { "id": "m17", "name": "Malfouf Mahchi", "arabicName": "ملفوف محشي", "category": "main", "calories": 120, "protein": 4.8, "carbs": 12.8, "fat": 5.6, "serving": "100g" },
    { "id": "m18", "name": "Moujadara", "arabicName": "مجدّرة", "category": "main", "calories": 113, "protein": 4.6, "carbs": 17.3, "fat": 2.6, "serving": "100g" },
    { "id": "m19", "name": "Moghrabia", "arabicName": "مغربية", "category": "main", "calories": 112, "protein": 5.5, "carbs": 12.5, "fat": 4.5, "serving": "100g" },
    { "id": "m20", "name": "Mousaka Batinjan", "arabicName": "مسقعة باذنجان", "category": "main", "calories": 116, "protein": 4, "carbs": 8, "fat": 8, "serving": "100g" },
    { "id": "m21", "name": "Riz a Dajaj", "arabicName": "رز بالدجاج", "category": "main", "calories": 137, "protein": 9.1, "carbs": 14.8, "fat": 4, "serving": "100g" },
    { "id": "m22", "name": "Riz bi Lahma", "arabicName": "رز باللحمة", "category": "main", "calories": 148, "protein": 8, "carbs": 15.7, "fat": 5.7, "serving": "100g" },
    { "id": "m23", "name": "Sayadia", "arabicName": "صيادية", "category": "main", "calories": 125, "protein": 8.5, "carbs": 12.8, "fat": 4, "serving": "100g" },
    { "id": "m24", "name": "Shawarma Dajaj", "arabicName": "شاورما دجاج", "category": "main", "calories": 210, "protein": 14, "carbs": 19, "fat": 8, "serving": "100g" },
    { "id": "m25", "name": "Shawarma Lahma", "arabicName": "شاورما لحمة", "category": "main", "calories": 240, "protein": 13, "carbs": 18, "fat": 12, "serving": "100g" },
    { "id": "m26", "name": "Tabboula", "arabicName": "تبّولة", "category": "main", "calories": 60, "protein": 1.5, "carbs": 8, "fat": 2.5, "serving": "100g" },
    { "id": "m27", "name": "Warak Enab", "arabicName": "ورق عنب", "category": "main", "calories": 140, "protein": 4, "carbs": 16, "fat": 7, "serving": "100g" },
    { "id": "m28", "name": "Yakhnat Bamia", "arabicName": "يخنة بامية", "category": "main", "calories": 100, "protein": 5.7, "carbs": 6.2, "fat": 5.7, "serving": "100g" },
    { "id": "m29", "name": "Yakhnat Fassoulia", "arabicName": "يخنة فاصوليا", "category": "main", "calories": 108, "protein": 6.2, "carbs": 8.5, "fat": 5.1, "serving": "100g" },
    { "id": "m30", "name": "Yakhnat Mouloukhia", "arabicName": "يخنة ملوخية", "category": "main", "calories": 102, "protein": 6.8, "carbs": 5.1, "fat": 6.2, "serving": "100g" },
    { "id": "m31", "name": "Beid bil Awarma", "arabicName": "بيض بالقاورما", "category": "main", "calories": 233, "protein": 14.6, "carbs": 2.6, "fat": 18.6, "serving": "100g" },
    { "id": "m32", "name": "Grilled Steak", "arabicName": "ستيك مشوي", "category": "main", "calories": 225, "protein": 26, "carbs": 0, "fat": 12, "serving": "100g" },
    { "id": "m33", "name": "Grilled Chicken", "arabicName": "دجاج مشوي", "category": "main", "calories": 190, "protein": 24, "carbs": 0, "fat": 9, "serving": "100g" },
    { "id": "m34", "name": "Labneh", "arabicName": "لبنة", "category": "main", "calories": 120, "protein": 8, "carbs": 6, "fat": 8, "serving": "100g" },
    { "id": "m35", "name": "Manoushe Zaatar", "arabicName": "منقوشة زعتر", "category": "main", "calories": 213, "protein": 5.3, "carbs": 28, "fat": 9.3, "serving": "100g" },
    # Desserts
    { "id": "d01", "name": "Baklava Mixed", "arabicName": "بقلاوة مشكّلة", "category": "dessert", "calories": 480, "protein": 5, "carbs": 55, "fat": 26, "serving": "100g" },
    { "id": "d15", "name": "Kounafa Kashta", "arabicName": "كنافة قشطة", "category": "dessert", "calories": 310, "protein": 5.8, "carbs": 35.5, "fat": 16.3, "serving": "100g" },
]
